server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: PROMOTION-SERVICE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  liquibase:
    change-log: 'classpath:db-changelog/changelog-master.xml'
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
    accounting-service:
      connectTimeout: 3000
      readTimeout: 3000
